"""create datasource table

Revision ID: 3f6d59a880be
Revises: d91ca96d5c95
Create Date: 2026-02-25 16:11:43.600660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6d59a880be'
down_revision: Union[str, Sequence[str], None] = 'd91ca96d5c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('db_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('database_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('datasources_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('datasources_pkey'))
    )
    # ### end Alembic commands ###
